--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3 (Debian 13.3-1)
-- Dumped by pg_dump version 13.3 (Debian 13.3-1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.taggit_taggeditem DROP CONSTRAINT taggit_taggeditem_tag_id_f4f5b767_fk_taggit_tag_id;
ALTER TABLE ONLY public.taggit_taggeditem DROP CONSTRAINT taggit_taggeditem_content_type_id_9957a03c_fk_django_co;
ALTER TABLE ONLY public.master_db_session DROP CONSTRAINT master_db_session_student_id_ca59e63c_fk_master_db;
ALTER TABLE ONLY public.master_db_session DROP CONSTRAINT master_db_session_schedule_id_1320b4ab_fk_master_db_schedule_id;
ALTER TABLE ONLY public.master_db_schedule DROP CONSTRAINT master_db_schedule_classroom_id_7dec42c9_fk_master_db;
ALTER TABLE ONLY public.master_db_customuser_user_permissions DROP CONSTRAINT master_db_customuser_permission_id_2dbbb0f8_fk_auth_perm;
ALTER TABLE ONLY public.master_db_customuser_groups DROP CONSTRAINT master_db_customuser_groups_group_id_be7a2fbb_fk_auth_group_id;
ALTER TABLE ONLY public.master_db_customuser_groups DROP CONSTRAINT master_db_customuser_customuser_id_d4fc8e39_fk_master_db;
ALTER TABLE ONLY public.master_db_customuser_user_permissions DROP CONSTRAINT master_db_customuser_customuser_id_068dff0a_fk_master_db;
ALTER TABLE ONLY public.master_db_classmetadata DROP CONSTRAINT master_db_classmetad_teacher_id_9261b72b_fk_master_db;
ALTER TABLE ONLY public.master_db_classmetadata_students DROP CONSTRAINT master_db_classmetad_customuser_id_0dced2c7_fk_master_db;
ALTER TABLE ONLY public.master_db_classmetadata DROP CONSTRAINT master_db_classmetad_course_id_a4e7e225_fk_master_db;
ALTER TABLE ONLY public.master_db_classmetadata_students DROP CONSTRAINT master_db_classmetad_classmetadata_id_18b2f363_fk_master_db;
ALTER TABLE ONLY public.master_db_calendar DROP CONSTRAINT master_db_calendar_user_id_5783cbd6_fk_master_db_customuser_id;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_user_id_c564eba6_fk_master_db_customuser_id;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;
DROP INDEX public.taggit_taggeditem_tag_id_f4f5b767;
DROP INDEX public.taggit_taggeditem_object_id_e2d7d1df;
DROP INDEX public.taggit_taggeditem_content_type_id_object_id_196cc965_idx;
DROP INDEX public.taggit_taggeditem_content_type_id_9957a03c;
DROP INDEX public.taggit_tag_slug_6be58b2c_like;
DROP INDEX public.taggit_tag_name_58eb2ed9_like;
DROP INDEX public.master_db_session_student_id_ca59e63c;
DROP INDEX public.master_db_session_schedule_id_1320b4ab;
DROP INDEX public.master_db_schedule_classroom_id_7dec42c9;
DROP INDEX public.master_db_s_time_st_3687ab_idx;
DROP INDEX public.master_db_s_student_f72458_idx;
DROP INDEX public.master_db_s_schedul_38b7a6_idx;
DROP INDEX public.master_db_customuser_user_permissions_permission_id_2dbbb0f8;
DROP INDEX public.master_db_customuser_user_permissions_customuser_id_068dff0a;
DROP INDEX public.master_db_customuser_mobile_ff0a9100_like;
DROP INDEX public.master_db_customuser_groups_group_id_be7a2fbb;
DROP INDEX public.master_db_customuser_groups_customuser_id_d4fc8e39;
DROP INDEX public.master_db_customuser_email_34752d40_like;
DROP INDEX public.master_db_course_name_a102d63d_like;
DROP INDEX public.master_db_classmetadata_teacher_id_9261b72b;
DROP INDEX public.master_db_classmetadata_students_customuser_id_0dced2c7;
DROP INDEX public.master_db_classmetadata_students_classmetadata_id_18b2f363;
DROP INDEX public.master_db_classmetadata_name_e026d62c_like;
DROP INDEX public.master_db_classmetadata_course_id_a4e7e225;
DROP INDEX public.master_db_calendar_user_id_5783cbd6;
DROP INDEX public.master_db_c_time_st_aa0106_idx;
DROP INDEX public.master_db_c_status_0e5524_idx;
DROP INDEX public.master_db_c_male_e11d83_idx;
DROP INDEX public.master_db_c_first_n_87b10f_idx;
DROP INDEX public.master_db_c_duratio_7c3de7_idx;
DROP INDEX public.master_db_c_course__cd1b38_idx;
DROP INDEX public.django_session_session_key_c0390e0f_like;
DROP INDEX public.django_session_expire_date_a5c62663;
DROP INDEX public.django_cron_cronjoblog_start_time_d68c0dd9;
DROP INDEX public.django_cron_cronjoblog_ran_at_time_7fed2751;
DROP INDEX public.django_cron_cronjoblog_end_time_7918602a;
DROP INDEX public.django_cron_cronjoblog_code_start_time_ran_at_time_8b50b8fa_idx;
DROP INDEX public.django_cron_cronjoblog_code_start_time_4fc78f9d_idx;
DROP INDEX public.django_cron_cronjoblog_code_is_success_ran_at_time_84da9606_idx;
DROP INDEX public.django_cron_cronjoblog_code_48865653_like;
DROP INDEX public.django_cron_cronjoblog_code_48865653;
DROP INDEX public.django_admin_log_user_id_c564eba6;
DROP INDEX public.django_admin_log_content_type_id_c4bce8eb;
DROP INDEX public.auth_permission_content_type_id_2f476e4b;
DROP INDEX public.auth_group_permissions_permission_id_84c5c92e;
DROP INDEX public.auth_group_permissions_group_id_b120cbf9;
DROP INDEX public.auth_group_name_a6ea08ec_like;
ALTER TABLE ONLY public.master_db_session DROP CONSTRAINT unique_session;
ALTER TABLE ONLY public.taggit_taggeditem DROP CONSTRAINT taggit_taggeditem_pkey;
ALTER TABLE ONLY public.taggit_taggeditem DROP CONSTRAINT taggit_taggeditem_content_type_id_object_i_4bb97a8e_uniq;
ALTER TABLE ONLY public.taggit_tag DROP CONSTRAINT taggit_tag_slug_key;
ALTER TABLE ONLY public.taggit_tag DROP CONSTRAINT taggit_tag_pkey;
ALTER TABLE ONLY public.taggit_tag DROP CONSTRAINT taggit_tag_name_key;
ALTER TABLE ONLY public.master_db_setting DROP CONSTRAINT master_db_setting_pkey;
ALTER TABLE ONLY public.master_db_session DROP CONSTRAINT master_db_session_pkey;
ALTER TABLE ONLY public.master_db_schedule DROP CONSTRAINT master_db_schedule_pkey;
ALTER TABLE ONLY public.master_db_log DROP CONSTRAINT master_db_log_pkey;
ALTER TABLE ONLY public.master_db_customuser_user_permissions DROP CONSTRAINT master_db_customuser_user_permissions_pkey;
ALTER TABLE ONLY public.master_db_customuser_user_permissions DROP CONSTRAINT master_db_customuser_use_customuser_id_permission_a797bcf9_uniq;
ALTER TABLE ONLY public.master_db_customuser DROP CONSTRAINT master_db_customuser_pkey;
ALTER TABLE ONLY public.master_db_customuser DROP CONSTRAINT master_db_customuser_mobile_key;
ALTER TABLE ONLY public.master_db_customuser_groups DROP CONSTRAINT master_db_customuser_groups_pkey;
ALTER TABLE ONLY public.master_db_customuser_groups DROP CONSTRAINT master_db_customuser_gro_customuser_id_group_id_c33e6386_uniq;
ALTER TABLE ONLY public.master_db_customuser DROP CONSTRAINT master_db_customuser_email_key;
ALTER TABLE ONLY public.master_db_course DROP CONSTRAINT master_db_course_pkey;
ALTER TABLE ONLY public.master_db_course DROP CONSTRAINT master_db_course_name_key;
ALTER TABLE ONLY public.master_db_classmetadata_students DROP CONSTRAINT master_db_classmetadata_students_pkey;
ALTER TABLE ONLY public.master_db_classmetadata DROP CONSTRAINT master_db_classmetadata_pkey;
ALTER TABLE ONLY public.master_db_classmetadata DROP CONSTRAINT master_db_classmetadata_name_key;
ALTER TABLE ONLY public.master_db_classmetadata_students DROP CONSTRAINT master_db_classmetadata__classmetadata_id_customu_f53b05b1_uniq;
ALTER TABLE ONLY public.master_db_calendar DROP CONSTRAINT master_db_calendar_pkey;
ALTER TABLE ONLY public.master_db_branch DROP CONSTRAINT master_db_branch_pkey;
ALTER TABLE ONLY public.django_session DROP CONSTRAINT django_session_pkey;
ALTER TABLE ONLY public.django_migrations DROP CONSTRAINT django_migrations_pkey;
ALTER TABLE ONLY public.django_cron_cronjoblog DROP CONSTRAINT django_cron_cronjoblog_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_name_key;
ALTER TABLE public.taggit_taggeditem ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.taggit_tag ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_setting ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_session ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_schedule ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_log ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_customuser_user_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_customuser_groups ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_customuser ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_course ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_classmetadata_students ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_classmetadata ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_calendar ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.master_db_branch ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_migrations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_cron_cronjoblog ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_content_type ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_admin_log ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_permission ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.taggit_taggeditem_id_seq;
DROP TABLE public.taggit_taggeditem;
DROP SEQUENCE public.taggit_tag_id_seq;
DROP TABLE public.taggit_tag;
DROP SEQUENCE public.master_db_setting_id_seq;
DROP TABLE public.master_db_setting;
DROP SEQUENCE public.master_db_session_id_seq;
DROP TABLE public.master_db_session;
DROP SEQUENCE public.master_db_schedule_id_seq;
DROP TABLE public.master_db_schedule;
DROP SEQUENCE public.master_db_log_id_seq;
DROP TABLE public.master_db_log;
DROP SEQUENCE public.master_db_customuser_user_permissions_id_seq;
DROP TABLE public.master_db_customuser_user_permissions;
DROP SEQUENCE public.master_db_customuser_id_seq;
DROP SEQUENCE public.master_db_customuser_groups_id_seq;
DROP TABLE public.master_db_customuser_groups;
DROP TABLE public.master_db_customuser;
DROP SEQUENCE public.master_db_course_id_seq;
DROP TABLE public.master_db_course;
DROP SEQUENCE public.master_db_classmetadata_students_id_seq;
DROP TABLE public.master_db_classmetadata_students;
DROP SEQUENCE public.master_db_classmetadata_id_seq;
DROP TABLE public.master_db_classmetadata;
DROP SEQUENCE public.master_db_calendar_id_seq;
DROP TABLE public.master_db_calendar;
DROP SEQUENCE public.master_db_branch_id_seq;
DROP TABLE public.master_db_branch;
DROP TABLE public.django_session;
DROP SEQUENCE public.django_migrations_id_seq;
DROP TABLE public.django_migrations;
DROP SEQUENCE public.django_cron_cronjoblog_id_seq;
DROP TABLE public.django_cron_cronjoblog;
DROP SEQUENCE public.django_content_type_id_seq;
DROP TABLE public.django_content_type;
DROP SEQUENCE public.django_admin_log_id_seq;
DROP TABLE public.django_admin_log;
DROP SEQUENCE public.auth_permission_id_seq;
DROP TABLE public.auth_permission;
DROP SEQUENCE public.auth_group_permissions_id_seq;
DROP TABLE public.auth_group_permissions;
DROP SEQUENCE public.auth_group_id_seq;
DROP TABLE public.auth_group;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO tfc_admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.auth_group_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_id_seq OWNER TO tfc_admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.auth_group_id_seq OWNED BY public.auth_group.id;


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO tfc_admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_permissions_id_seq OWNER TO tfc_admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.auth_group_permissions_id_seq OWNED BY public.auth_group_permissions.id;


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO tfc_admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.auth_permission_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_permission_id_seq OWNER TO tfc_admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.auth_permission_id_seq OWNED BY public.auth_permission.id;


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO tfc_admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.django_admin_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_admin_log_id_seq OWNER TO tfc_admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.django_admin_log_id_seq OWNED BY public.django_admin_log.id;


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO tfc_admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.django_content_type_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_content_type_id_seq OWNER TO tfc_admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.django_content_type_id_seq OWNED BY public.django_content_type.id;


--
-- Name: django_cron_cronjoblog; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.django_cron_cronjoblog (
    id bigint NOT NULL,
    code character varying(64) NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    is_success boolean NOT NULL,
    message text NOT NULL,
    ran_at_time time without time zone
);


ALTER TABLE public.django_cron_cronjoblog OWNER TO tfc_admin;

--
-- Name: django_cron_cronjoblog_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.django_cron_cronjoblog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_cron_cronjoblog_id_seq OWNER TO tfc_admin;

--
-- Name: django_cron_cronjoblog_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.django_cron_cronjoblog_id_seq OWNED BY public.django_cron_cronjoblog.id;


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO tfc_admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_migrations_id_seq OWNER TO tfc_admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.django_migrations_id_seq OWNED BY public.django_migrations.id;


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO tfc_admin;

--
-- Name: master_db_branch; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_branch (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    uuid uuid NOT NULL,
    "desc" text,
    addr text NOT NULL,
    short_adr text NOT NULL,
    phone text NOT NULL
);


ALTER TABLE public.master_db_branch OWNER TO tfc_admin;

--
-- Name: master_db_branch_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_branch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_branch_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_branch_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_branch_id_seq OWNED BY public.master_db_branch.id;


--
-- Name: master_db_calendar; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_calendar (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    uuid uuid NOT NULL,
    "desc" text,
    name text NOT NULL,
    time_start timestamp with time zone NOT NULL,
    time_end timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.master_db_calendar OWNER TO tfc_admin;

--
-- Name: master_db_calendar_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_calendar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_calendar_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_calendar_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_calendar_id_seq OWNED BY public.master_db_calendar.id;


--
-- Name: master_db_classmetadata; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_classmetadata (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    uuid uuid NOT NULL,
    "desc" text,
    name text NOT NULL,
    status text NOT NULL,
    course_id bigint NOT NULL,
    teacher_id bigint
);


ALTER TABLE public.master_db_classmetadata OWNER TO tfc_admin;

--
-- Name: master_db_classmetadata_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_classmetadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_classmetadata_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_classmetadata_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_classmetadata_id_seq OWNED BY public.master_db_classmetadata.id;


--
-- Name: master_db_classmetadata_students; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_classmetadata_students (
    id bigint NOT NULL,
    classmetadata_id bigint NOT NULL,
    customuser_id bigint NOT NULL
);


ALTER TABLE public.master_db_classmetadata_students OWNER TO tfc_admin;

--
-- Name: master_db_classmetadata_students_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_classmetadata_students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_classmetadata_students_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_classmetadata_students_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_classmetadata_students_id_seq OWNED BY public.master_db_classmetadata_students.id;


--
-- Name: master_db_course; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_course (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    uuid uuid NOT NULL,
    "desc" text,
    name text NOT NULL,
    duration smallint NOT NULL
);


ALTER TABLE public.master_db_course OWNER TO tfc_admin;

--
-- Name: master_db_course_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_course_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_course_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_course_id_seq OWNED BY public.master_db_course.id;


--
-- Name: master_db_customuser; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    uuid uuid NOT NULL,
    email character varying(254) NOT NULL,
    birth_date date,
    mobile character varying(15) NOT NULL,
    male boolean,
    address text,
    avatar character varying(100),
    date_joined timestamp with time zone NOT NULL,
    date_updated timestamp with time zone NOT NULL
);


ALTER TABLE public.master_db_customuser OWNER TO tfc_admin;

--
-- Name: master_db_customuser_groups; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.master_db_customuser_groups OWNER TO tfc_admin;

--
-- Name: master_db_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_customuser_groups_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_customuser_groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_customuser_groups_id_seq OWNED BY public.master_db_customuser_groups.id;


--
-- Name: master_db_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_customuser_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_customuser_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_customuser_id_seq OWNED BY public.master_db_customuser.id;


--
-- Name: master_db_customuser_user_permissions; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.master_db_customuser_user_permissions OWNER TO tfc_admin;

--
-- Name: master_db_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_customuser_user_permissions_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_customuser_user_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_customuser_user_permissions_id_seq OWNED BY public.master_db_customuser_user_permissions.id;


--
-- Name: master_db_log; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_log (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    uuid uuid NOT NULL,
    "desc" text
);


ALTER TABLE public.master_db_log OWNER TO tfc_admin;

--
-- Name: master_db_log_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_log_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_log_id_seq OWNED BY public.master_db_log.id;


--
-- Name: master_db_schedule; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_schedule (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    uuid uuid NOT NULL,
    "desc" text,
    time_start timestamp with time zone NOT NULL,
    time_end timestamp with time zone NOT NULL,
    classroom_id bigint NOT NULL
);


ALTER TABLE public.master_db_schedule OWNER TO tfc_admin;

--
-- Name: master_db_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_schedule_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_schedule_id_seq OWNED BY public.master_db_schedule.id;


--
-- Name: master_db_session; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_session (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    uuid uuid NOT NULL,
    "desc" text,
    homework smallint,
    status boolean,
    schedule_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.master_db_session OWNER TO tfc_admin;

--
-- Name: master_db_session_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_session_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_session_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_session_id_seq OWNED BY public.master_db_session.id;


--
-- Name: master_db_setting; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.master_db_setting (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    uuid uuid NOT NULL,
    "desc" text,
    name text NOT NULL,
    value text NOT NULL
);


ALTER TABLE public.master_db_setting OWNER TO tfc_admin;

--
-- Name: master_db_setting_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.master_db_setting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.master_db_setting_id_seq OWNER TO tfc_admin;

--
-- Name: master_db_setting_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.master_db_setting_id_seq OWNED BY public.master_db_setting.id;


--
-- Name: taggit_tag; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.taggit_tag (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL
);


ALTER TABLE public.taggit_tag OWNER TO tfc_admin;

--
-- Name: taggit_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.taggit_tag_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.taggit_tag_id_seq OWNER TO tfc_admin;

--
-- Name: taggit_tag_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.taggit_tag_id_seq OWNED BY public.taggit_tag.id;


--
-- Name: taggit_taggeditem; Type: TABLE; Schema: public; Owner: tfc_admin
--

CREATE TABLE public.taggit_taggeditem (
    id integer NOT NULL,
    object_id integer NOT NULL,
    content_type_id integer NOT NULL,
    tag_id integer NOT NULL
);


ALTER TABLE public.taggit_taggeditem OWNER TO tfc_admin;

--
-- Name: taggit_taggeditem_id_seq; Type: SEQUENCE; Schema: public; Owner: tfc_admin
--

CREATE SEQUENCE public.taggit_taggeditem_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.taggit_taggeditem_id_seq OWNER TO tfc_admin;

--
-- Name: taggit_taggeditem_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: tfc_admin
--

ALTER SEQUENCE public.taggit_taggeditem_id_seq OWNED BY public.taggit_taggeditem.id;


--
-- Name: auth_group id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_group ALTER COLUMN id SET DEFAULT nextval('public.auth_group_id_seq'::regclass);


--
-- Name: auth_group_permissions id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_group_permissions ALTER COLUMN id SET DEFAULT nextval('public.auth_group_permissions_id_seq'::regclass);


--
-- Name: auth_permission id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_permission ALTER COLUMN id SET DEFAULT nextval('public.auth_permission_id_seq'::regclass);


--
-- Name: django_admin_log id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_admin_log ALTER COLUMN id SET DEFAULT nextval('public.django_admin_log_id_seq'::regclass);


--
-- Name: django_content_type id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_content_type ALTER COLUMN id SET DEFAULT nextval('public.django_content_type_id_seq'::regclass);


--
-- Name: django_cron_cronjoblog id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_cron_cronjoblog ALTER COLUMN id SET DEFAULT nextval('public.django_cron_cronjoblog_id_seq'::regclass);


--
-- Name: django_migrations id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_migrations ALTER COLUMN id SET DEFAULT nextval('public.django_migrations_id_seq'::regclass);


--
-- Name: master_db_branch id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_branch ALTER COLUMN id SET DEFAULT nextval('public.master_db_branch_id_seq'::regclass);


--
-- Name: master_db_calendar id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_calendar ALTER COLUMN id SET DEFAULT nextval('public.master_db_calendar_id_seq'::regclass);


--
-- Name: master_db_classmetadata id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata ALTER COLUMN id SET DEFAULT nextval('public.master_db_classmetadata_id_seq'::regclass);


--
-- Name: master_db_classmetadata_students id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata_students ALTER COLUMN id SET DEFAULT nextval('public.master_db_classmetadata_students_id_seq'::regclass);


--
-- Name: master_db_course id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_course ALTER COLUMN id SET DEFAULT nextval('public.master_db_course_id_seq'::regclass);


--
-- Name: master_db_customuser id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser ALTER COLUMN id SET DEFAULT nextval('public.master_db_customuser_id_seq'::regclass);


--
-- Name: master_db_customuser_groups id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_groups ALTER COLUMN id SET DEFAULT nextval('public.master_db_customuser_groups_id_seq'::regclass);


--
-- Name: master_db_customuser_user_permissions id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_user_permissions ALTER COLUMN id SET DEFAULT nextval('public.master_db_customuser_user_permissions_id_seq'::regclass);


--
-- Name: master_db_log id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_log ALTER COLUMN id SET DEFAULT nextval('public.master_db_log_id_seq'::regclass);


--
-- Name: master_db_schedule id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_schedule ALTER COLUMN id SET DEFAULT nextval('public.master_db_schedule_id_seq'::regclass);


--
-- Name: master_db_session id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_session ALTER COLUMN id SET DEFAULT nextval('public.master_db_session_id_seq'::regclass);


--
-- Name: master_db_setting id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_setting ALTER COLUMN id SET DEFAULT nextval('public.master_db_setting_id_seq'::regclass);


--
-- Name: taggit_tag id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.taggit_tag ALTER COLUMN id SET DEFAULT nextval('public.taggit_tag_id_seq'::regclass);


--
-- Name: taggit_taggeditem id; Type: DEFAULT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.taggit_taggeditem ALTER COLUMN id SET DEFAULT nextval('public.taggit_taggeditem_id_seq'::regclass);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.auth_group (id, name) FROM stdin;
1	Student
2	Teacher
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add cron job log	6	add_cronjoblog
22	Can change cron job log	6	change_cronjoblog
23	Can delete cron job log	6	delete_cronjoblog
24	Can view cron job log	6	view_cronjoblog
25	Can add tag	7	add_tag
26	Can change tag	7	change_tag
27	Can delete tag	7	delete_tag
28	Can view tag	7	view_tag
29	Can add tagged item	8	add_taggeditem
30	Can change tagged item	8	change_taggeditem
31	Can delete tagged item	8	delete_taggeditem
32	Can view tagged item	8	view_taggeditem
33	Can add user	9	add_customuser
34	Can change user	9	change_customuser
35	Can delete user	9	delete_customuser
36	Can view user	9	view_customuser
37	Can add branch	10	add_branch
38	Can change branch	10	change_branch
39	Can delete branch	10	delete_branch
40	Can view branch	10	view_branch
41	Can add class	11	add_classmetadata
42	Can change class	11	change_classmetadata
43	Can delete class	11	delete_classmetadata
44	Can view class	11	view_classmetadata
45	Can add table	12	add_metatable
46	Can change table	12	change_metatable
47	Can delete table	12	delete_metatable
48	Can view table	12	view_metatable
49	Can add schedule	13	add_schedule
50	Can change schedule	13	change_schedule
51	Can delete schedule	13	delete_schedule
52	Can view schedule	13	view_schedule
53	Can add setting	14	add_setting
54	Can change setting	14	change_setting
55	Can delete setting	14	delete_setting
56	Can view setting	14	view_setting
57	Can add session	15	add_session
58	Can change session	15	change_session
59	Can delete session	15	delete_session
60	Can view session	15	view_session
61	Can add log	16	add_log
62	Can change log	16	change_log
63	Can delete log	16	delete_log
64	Can view log	16	view_log
65	Can add course	17	add_course
66	Can change course	17	change_course
67	Can delete course	17	delete_course
68	Can view course	17	view_course
69	Can add calendar	18	add_calendar
70	Can change calendar	18	change_calendar
71	Can delete calendar	18	delete_calendar
72	Can view calendar	18	view_calendar
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2021-08-01 13:05:58.48229+07	1	 	2	[{"changed": {"fields": ["Avatar"]}}]	9	1
2	2021-08-01 14:53:25.936247+07	2	Stu dent	1	[{"added": {}}]	9	1
3	2021-08-01 14:53:42.30776+07	2	Stu dent	2	[]	9	1
4	2021-08-01 14:54:25.173833+07	3	Sang Vo	1	[{"added": {}}]	9	1
5	2021-08-01 14:54:48.7094+07	1	Student	1	[{"added": {}}]	3	1
6	2021-08-01 14:56:15.501127+07	2	Stu dent	2	[{"changed": {"fields": ["Groups"]}}]	9	1
7	2021-08-01 14:56:37.674987+07	2	Stu dent	2	[{"changed": {"fields": ["Groups"]}}]	9	1
8	2021-08-01 14:58:39.689118+07	4	teacher 2	1	[{"added": {}}]	9	1
9	2021-08-01 14:58:44.263619+07	4	teacher 2	2	[]	9	1
10	2021-08-01 14:59:41.087762+07	1	IELTS READING	1	[{"added": {}}]	17	1
11	2021-08-01 15:00:03.156552+07	2	IELTS WRITING	1	[{"added": {}}]	17	1
12	2021-08-01 15:01:44.166552+07	1	Class 1 - Reading skills	1	[{"added": {}}]	11	1
13	2021-08-01 15:02:33.666794+07	2	Class 2 - writing	1	[{"added": {}}]	11	1
14	2021-08-01 15:02:52.818262+07	2	Class 2 - Writing skills	2	[{"changed": {"fields": ["Name"]}}]	11	1
15	2021-08-01 15:03:44.671749+07	1	Class 1 - Reading skills, 19:30 ~ 21:00	1	[{"added": {}}]	13	1
16	2021-08-01 15:04:24.044592+07	2	Class 1 - Reading skills, 17:30 ~ 19:00	1	[{"added": {}}]	13	1
17	2021-08-01 15:05:02.878229+07	3	Class 1 - Reading skills, 19:30 ~ 21:00	1	[{"added": {}}]	13	1
18	2021-08-01 15:05:34.061994+07	4	Class 2 - Writing skills, 18:00 ~ 20:00	1	[{"added": {}}]	13	1
19	2021-08-01 15:06:16.93449+07	5	Class 2 - Writing skills, 17:00 ~ 19:00	1	[{"added": {}}]	13	1
20	2021-08-01 15:16:36.87287+07	2	Stu dent	2	[{"changed": {"fields": ["Male"]}}]	9	1
21	2021-08-01 15:16:43.640507+07	3	Sang Vo	2	[]	9	1
22	2021-08-01 15:16:49.708312+07	4	teacher 2	2	[{"changed": {"fields": ["Male"]}}]	9	1
23	2021-08-01 21:19:29.977289+07	2	Stu dent	2	[{"changed": {"fields": ["Avatar"]}}]	9	1
24	2021-08-01 21:19:44.972523+07	3	Sang Vo	2	[{"changed": {"fields": ["Avatar"]}}]	9	1
25	2021-08-01 21:19:56.236958+07	3	Sang Vo	2	[]	9	1
26	2021-08-02 23:05:41.859924+07	2	Stu dent	2	[{"changed": {"fields": ["Groups"]}}]	9	1
27	2021-08-02 23:13:35.646328+07	2	Teacher	1	[{"added": {}}]	3	1
28	2021-08-02 23:13:46.585669+07	2	Stu dent	2	[{"changed": {"fields": ["Groups"]}}]	9	1
29	2021-08-02 23:30:34.752635+07	2	Stu dent	2	[{"changed": {"fields": ["Groups"]}}]	9	1
30	2021-08-14 18:17:50.291913+07	3	Sang Vo	2	[{"changed": {"fields": ["Groups"]}}]	9	1
31	2021-08-24 08:36:38.443691+07	2	Class 2 - Writing skills	2	[]	11	1
32	2021-08-24 08:36:44.893533+07	2	Class 2 - Writing skills	2	[]	11	1
33	2021-08-24 08:36:49.830679+07	1	Class 1 - Reading skills	2	[{"changed": {"fields": ["Students"]}}]	11	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	django_cron	cronjoblog
7	taggit	tag
8	taggit	taggeditem
9	master_db	customuser
10	master_db	branch
11	master_db	classmetadata
12	master_db	metatable
13	master_db	schedule
14	master_db	setting
15	master_db	session
16	master_db	log
17	master_db	course
18	master_db	calendar
\.


--
-- Data for Name: django_cron_cronjoblog; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.django_cron_cronjoblog (id, code, start_time, end_time, is_success, message, ran_at_time) FROM stdin;
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2021-08-01 13:04:16.585079+07
2	taggit	0001_initial	2021-08-01 13:04:16.650464+07
3	auth	0001_initial	2021-08-01 13:04:16.738326+07
4	master_db	0001_initial	2021-08-01 13:04:17.345464+07
5	admin	0001_initial	2021-08-01 13:04:17.396879+07
6	admin	0002_logentry_remove_auto_add	2021-08-01 13:04:17.41829+07
7	admin	0003_logentry_add_action_flag_choices	2021-08-01 13:04:17.437253+07
8	contenttypes	0002_remove_content_type_name	2021-08-01 13:04:17.478617+07
9	auth	0002_alter_permission_name_max_length	2021-08-01 13:04:17.501483+07
10	auth	0003_alter_user_email_max_length	2021-08-01 13:04:17.525193+07
11	auth	0004_alter_user_username_opts	2021-08-01 13:04:17.575295+07
12	auth	0005_alter_user_last_login_null	2021-08-01 13:04:17.588272+07
13	auth	0006_require_contenttypes_0002	2021-08-01 13:04:17.592173+07
14	auth	0007_alter_validators_add_error_messages	2021-08-01 13:04:17.604765+07
15	auth	0008_alter_user_username_max_length	2021-08-01 13:04:17.617896+07
16	auth	0009_alter_user_last_name_max_length	2021-08-01 13:04:17.63038+07
17	auth	0010_alter_group_name_max_length	2021-08-01 13:04:17.65496+07
18	auth	0011_update_proxy_permissions	2021-08-01 13:04:17.678519+07
19	auth	0012_alter_user_first_name_max_length	2021-08-01 13:04:17.691668+07
20	django_cron	0001_initial	2021-08-01 13:04:17.755302+07
21	django_cron	0002_remove_max_length_from_CronJobLog_message	2021-08-01 13:04:17.762737+07
22	django_cron	0003_alter_cronjoblog_id	2021-08-01 13:04:17.818053+07
23	sessions	0001_initial	2021-08-01 13:04:17.854551+07
24	taggit	0002_auto_20150616_2121	2021-08-01 13:04:17.871092+07
25	taggit	0003_taggeditem_add_unique_index	2021-08-01 13:04:17.89058+07
26	master_db	0002_auto_20210824_0914	2021-08-24 09:24:46.540255+07
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
t47784acqu49z2e8vkvwwge9ggu73lqd	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mA4bT:CVrWV4BrVf6JOvVzwe1v456vbUiadIoRkvRdg_7Ieaw	2021-08-15 13:05:39.947928+07
mx8wxt37lls06b3vrxtw5yam9zzszvly	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mA6Gt:QYBjWM1ZNOhru_HgfazKgOI1YL2pKaILJFuLGu5AC58	2021-08-15 14:52:31.88384+07
mj9ujwy9dp5edogu1t00bsf9hkjnkblf	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mAA3S:xLyWiolFblS__8fjL14GZiU4ztXIQSEXJq-93iSIHoo	2021-08-15 18:54:54.463607+07
9x0rs5bcrwr69paeeazbgntonx6e5prh	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mAAXZ:IHnflvok13I9C9TAHlRaYej9CcNtrn5-tzsHUoCyVDY	2021-08-15 19:26:01.878589+07
c7821z3cl19t93ysm3cioczksyo9dkpj	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mACJ4:a1xKIiK2YVgRkwMOjXCKyCdzAwbhI-zh3su82MvSysI	2021-08-15 21:19:10.440741+07
v73sbbqexyd8exjob8v7212o8ea5cq53	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mAaRT:qSfflsHVtvYOgUUbOltFq-9g3Lr0QVr7tc2d-5ZRtWA	2021-08-16 23:05:27.582083+07
9cas6kga8f55713juwmqqpgk2b36mbc5	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mBUi3:WjL-T-G43FqRr5ERxjxGZ6X9A5WBI21U54VOle41nJ4	2021-08-19 11:10:19.946145+07
2wlshbpgp9xx98336pvvd6ilk39m8d95	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mE6uU:wIgY4CeHe2GGniWbAFyM2HhlN3Xd0_QCE2RzaP_Gb2c	2021-08-26 16:21:58.950188+07
o3hr7id6vtkeoweptqpupi7ayc5oz776	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mEreE:yRTdFaX73tdDoRwvnHH0FaFfL0l0Zu7SW9Xmm2IE78E	2021-08-28 18:16:18.964315+07
y12d17gfb3ueqxd3i6xjk5e62r6vw5ez	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mGXEx:Jkk_8gtxtqiHk8bQnk7aU8i55IF8tNrncdHYiFJyOEA	2021-09-02 08:53:07.195147+07
q8f41ff437mljbdhgd16sspkae1iqvau	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mILKs:tX2uVHU7tZxlIxT8mpsgdnAEVnFiq-4ulQN5Lj97Wds	2021-09-07 08:34:42.155762+07
1b6ff34xpmnw10mqv4ec7n99pjlm57r0	.eJxVjEsOwjAMBe-SNYrIp63Nkn3PUNmxQwsokfpZIe4OlbqA7ZuZ9zIDbes4bIvOwyTmYpw5_W5M6aFlB3Kncqs21bLOE9tdsQddbF9Fn9fD_TsYaRm_NWFCD943ioAxSPDC4LjFNkbX5NTFDtSjBo2CQo5TTJADnTlDlwHM-wPNJDfL:1mMnxd:4UalmrILFjWfhXK6AN_zGR3rtT0gJFLVEIVtEeeh-Po	2021-09-19 15:57:09.069942+07
\.


--
-- Data for Name: master_db_branch; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_branch (id, created, modified, uuid, "desc", addr, short_adr, phone) FROM stdin;
\.


--
-- Data for Name: master_db_calendar; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_calendar (id, created, modified, uuid, "desc", name, time_start, time_end, user_id) FROM stdin;
\.


--
-- Data for Name: master_db_classmetadata; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_classmetadata (id, created, modified, uuid, "desc", name, status, course_id, teacher_id) FROM stdin;
2	2021-08-01 15:02:33.655639+07	2021-08-24 08:36:44.891438+07	2fefa883-3754-4605-a251-8e3fa5616e6f	Let's study writing	Class 2 - Writing skills	better	2	4
1	2021-08-01 15:01:44.153907+07	2021-08-24 08:36:49.827389+07	09273655-6844-497c-bf42-2bc61a0d7305	Hello, let's study reading	Class 1 - Reading skills	Good	1	4
\.


--
-- Data for Name: master_db_classmetadata_students; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_classmetadata_students (id, classmetadata_id, customuser_id) FROM stdin;
1	1	2
2	2	3
3	1	3
\.


--
-- Data for Name: master_db_course; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_course (id, created, modified, uuid, "desc", name, duration) FROM stdin;
1	2021-08-01 14:59:41.072984+07	2021-08-01 14:59:41.072984+07	eea04403-8e62-4400-903b-352d4488ae23	Reading is fun!	IELTS READING	3
2	2021-08-01 15:00:03.144259+07	2021-08-01 15:00:03.144259+07	ec911dca-7210-43bb-9761-e4d93b6b25c1	Writing is fun	IELTS WRITING	3
\.


--
-- Data for Name: master_db_customuser; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_customuser (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, uuid, email, birth_date, mobile, male, address, avatar, date_joined, date_updated) FROM stdin;
4	pbkdf2_sha256$260000$p03riSKrXhZ7yRg9yA7DUv$7bxZXCQWVVPDazQ4VZmbVrFdQX2OHNMZTDu9n7VtN14=	\N	f	teacher	2	f	t	dd8f2042-bdf6-4e45-860d-bd7335d28513	teacher1@tfc.com	2021-08-01	0987654321	t	595 Le Hong Phong st	users/dd8f2042-bdf6-4e45-860d-bd7335d28513/profile.jpg	2021-08-01 14:58:39.68701+07	2021-08-01 15:16:49.702772+07
2	pbkdf2_sha256$260000$mfn9P7j86TTHprCcbcvWox$1TcX23PHOKJKCOmwePOfhrzokfSJK/Jot+9eKIT/MZ4=	2021-08-14 18:17:19.420368+07	f	Stu	dent	f	t	701f1342-a12d-46b9-b471-70d4d4955fbf	student1@tfc.com	2001-04-27	0707083371	t	497 Hòa Hảo, p7, Q10, TPHCM	users/701f1342-a12d-46b9-b471-70d4d4955fbf/profile_V4HuU8q.jpg	2021-08-01 14:53:25.93444+07	2021-08-02 23:30:34.74574+07
3	pbkdf2_sha256$260000$ddSbtqcfxG3BhmCUzde5zo$O7b7zFnsRRibqTTJ8zeKiVqEnJon7TInKLfm4n7iU2E=	2021-08-29 15:22:15.400447+07	f	Sang	Vo	f	t	13e08dd3-c37f-41c3-b467-028d599d180b	student2@tfc.com	2021-08-01	0707083372	f	877 Le Hong Phong st	users/13e08dd3-c37f-41c3-b467-028d599d180b/profile_xl15hxI.jpg	2021-08-01 14:54:25.17126+07	2021-08-14 18:17:50.285539+07
1	pbkdf2_sha256$260000$0myfTj3dWK4PKJxeAs8WLX$48KDavCSheL0xGugIa4ZAvr+Zt50OtY8HtmEogoaP7w=	2021-09-05 15:57:09.061014+07	t			t	t	dc311b1e-1c92-45a0-b47e-9576aad10e04	owner@localhost.com	\N	0999999999	\N		users/dc311b1e-1c92-45a0-b47e-9576aad10e04/profile.jpg	2021-08-01 13:05:34.277147+07	2021-08-01 13:05:58.476404+07
\.


--
-- Data for Name: master_db_customuser_groups; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_customuser_groups (id, customuser_id, group_id) FROM stdin;
2	2	1
4	3	1
5	3	2
\.


--
-- Data for Name: master_db_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: master_db_log; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_log (id, created, modified, uuid, "desc") FROM stdin;
\.


--
-- Data for Name: master_db_schedule; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_schedule (id, created, modified, uuid, "desc", time_start, time_end, classroom_id) FROM stdin;
1	2021-08-01 15:03:44.666661+07	2021-08-01 15:03:44.666661+07	89f74b88-3022-4bac-9ccb-0e14958ff542	First class	2021-08-01 19:30:00+07	2021-08-01 21:00:00+07	1
2	2021-08-01 15:04:24.039459+07	2021-08-01 15:04:24.039459+07	e536a76b-a265-4a94-bc2a-2285ef2a4be3	Second class	2021-08-03 17:30:00+07	2021-08-03 19:00:00+07	1
3	2021-08-01 15:05:02.873474+07	2021-08-01 15:05:02.873474+07	0f39ce74-0da0-4112-9163-d3c005d733c0	final class	2021-08-05 19:30:00+07	2021-08-05 21:00:00+07	1
4	2021-08-01 15:05:34.056818+07	2021-08-01 15:05:34.056818+07	0fc933cd-d399-4456-82e5-ed7c56a409ee	hello	2021-08-02 18:00:00+07	2021-08-02 20:00:00+07	2
5	2021-08-01 15:06:16.929313+07	2021-08-01 15:06:16.929313+07	27e9bfc9-716c-4cc7-9b7d-5087a4e31e4a	second class	2021-08-04 17:00:00+07	2021-08-04 19:00:00+07	2
\.


--
-- Data for Name: master_db_session; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_session (id, created, modified, uuid, "desc", homework, status, schedule_id, student_id) FROM stdin;
\.


--
-- Data for Name: master_db_setting; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.master_db_setting (id, created, modified, uuid, "desc", name, value) FROM stdin;
\.


--
-- Data for Name: taggit_tag; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.taggit_tag (id, name, slug) FROM stdin;
1	reading	reading
2	writing	writing
\.


--
-- Data for Name: taggit_taggeditem; Type: TABLE DATA; Schema: public; Owner: tfc_admin
--

COPY public.taggit_taggeditem (id, object_id, content_type_id, tag_id) FROM stdin;
1	1	17	1
2	2	17	2
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 33, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_cron_cronjoblog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.django_cron_cronjoblog_id_seq', 1, false);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 26, true);


--
-- Name: master_db_branch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_branch_id_seq', 1, false);


--
-- Name: master_db_calendar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_calendar_id_seq', 1, false);


--
-- Name: master_db_classmetadata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_classmetadata_id_seq', 2, true);


--
-- Name: master_db_classmetadata_students_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_classmetadata_students_id_seq', 3, true);


--
-- Name: master_db_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_course_id_seq', 2, true);


--
-- Name: master_db_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_customuser_groups_id_seq', 5, true);


--
-- Name: master_db_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_customuser_id_seq', 4, true);


--
-- Name: master_db_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_customuser_user_permissions_id_seq', 1, false);


--
-- Name: master_db_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_log_id_seq', 1, false);


--
-- Name: master_db_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_schedule_id_seq', 5, true);


--
-- Name: master_db_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_session_id_seq', 1, false);


--
-- Name: master_db_setting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.master_db_setting_id_seq', 1, false);


--
-- Name: taggit_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.taggit_tag_id_seq', 2, true);


--
-- Name: taggit_taggeditem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tfc_admin
--

SELECT pg_catalog.setval('public.taggit_taggeditem_id_seq', 2, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_cron_cronjoblog django_cron_cronjoblog_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_cron_cronjoblog
    ADD CONSTRAINT django_cron_cronjoblog_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: master_db_branch master_db_branch_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_branch
    ADD CONSTRAINT master_db_branch_pkey PRIMARY KEY (id);


--
-- Name: master_db_calendar master_db_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_calendar
    ADD CONSTRAINT master_db_calendar_pkey PRIMARY KEY (id);


--
-- Name: master_db_classmetadata_students master_db_classmetadata__classmetadata_id_customu_f53b05b1_uniq; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata_students
    ADD CONSTRAINT master_db_classmetadata__classmetadata_id_customu_f53b05b1_uniq UNIQUE (classmetadata_id, customuser_id);


--
-- Name: master_db_classmetadata master_db_classmetadata_name_key; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata
    ADD CONSTRAINT master_db_classmetadata_name_key UNIQUE (name);


--
-- Name: master_db_classmetadata master_db_classmetadata_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata
    ADD CONSTRAINT master_db_classmetadata_pkey PRIMARY KEY (id);


--
-- Name: master_db_classmetadata_students master_db_classmetadata_students_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata_students
    ADD CONSTRAINT master_db_classmetadata_students_pkey PRIMARY KEY (id);


--
-- Name: master_db_course master_db_course_name_key; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_course
    ADD CONSTRAINT master_db_course_name_key UNIQUE (name);


--
-- Name: master_db_course master_db_course_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_course
    ADD CONSTRAINT master_db_course_pkey PRIMARY KEY (id);


--
-- Name: master_db_customuser master_db_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser
    ADD CONSTRAINT master_db_customuser_email_key UNIQUE (email);


--
-- Name: master_db_customuser_groups master_db_customuser_gro_customuser_id_group_id_c33e6386_uniq; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_groups
    ADD CONSTRAINT master_db_customuser_gro_customuser_id_group_id_c33e6386_uniq UNIQUE (customuser_id, group_id);


--
-- Name: master_db_customuser_groups master_db_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_groups
    ADD CONSTRAINT master_db_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: master_db_customuser master_db_customuser_mobile_key; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser
    ADD CONSTRAINT master_db_customuser_mobile_key UNIQUE (mobile);


--
-- Name: master_db_customuser master_db_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser
    ADD CONSTRAINT master_db_customuser_pkey PRIMARY KEY (id);


--
-- Name: master_db_customuser_user_permissions master_db_customuser_use_customuser_id_permission_a797bcf9_uniq; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_user_permissions
    ADD CONSTRAINT master_db_customuser_use_customuser_id_permission_a797bcf9_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: master_db_customuser_user_permissions master_db_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_user_permissions
    ADD CONSTRAINT master_db_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: master_db_log master_db_log_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_log
    ADD CONSTRAINT master_db_log_pkey PRIMARY KEY (id);


--
-- Name: master_db_schedule master_db_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_schedule
    ADD CONSTRAINT master_db_schedule_pkey PRIMARY KEY (id);


--
-- Name: master_db_session master_db_session_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_session
    ADD CONSTRAINT master_db_session_pkey PRIMARY KEY (id);


--
-- Name: master_db_setting master_db_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_setting
    ADD CONSTRAINT master_db_setting_pkey PRIMARY KEY (id);


--
-- Name: taggit_tag taggit_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.taggit_tag
    ADD CONSTRAINT taggit_tag_name_key UNIQUE (name);


--
-- Name: taggit_tag taggit_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.taggit_tag
    ADD CONSTRAINT taggit_tag_pkey PRIMARY KEY (id);


--
-- Name: taggit_tag taggit_tag_slug_key; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.taggit_tag
    ADD CONSTRAINT taggit_tag_slug_key UNIQUE (slug);


--
-- Name: taggit_taggeditem taggit_taggeditem_content_type_id_object_i_4bb97a8e_uniq; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.taggit_taggeditem
    ADD CONSTRAINT taggit_taggeditem_content_type_id_object_i_4bb97a8e_uniq UNIQUE (content_type_id, object_id, tag_id);


--
-- Name: taggit_taggeditem taggit_taggeditem_pkey; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.taggit_taggeditem
    ADD CONSTRAINT taggit_taggeditem_pkey PRIMARY KEY (id);


--
-- Name: master_db_session unique_session; Type: CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_session
    ADD CONSTRAINT unique_session UNIQUE (student_id, schedule_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_cron_cronjoblog_code_48865653; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_cron_cronjoblog_code_48865653 ON public.django_cron_cronjoblog USING btree (code);


--
-- Name: django_cron_cronjoblog_code_48865653_like; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_cron_cronjoblog_code_48865653_like ON public.django_cron_cronjoblog USING btree (code varchar_pattern_ops);


--
-- Name: django_cron_cronjoblog_code_is_success_ran_at_time_84da9606_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_cron_cronjoblog_code_is_success_ran_at_time_84da9606_idx ON public.django_cron_cronjoblog USING btree (code, is_success, ran_at_time);


--
-- Name: django_cron_cronjoblog_code_start_time_4fc78f9d_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_cron_cronjoblog_code_start_time_4fc78f9d_idx ON public.django_cron_cronjoblog USING btree (code, start_time);


--
-- Name: django_cron_cronjoblog_code_start_time_ran_at_time_8b50b8fa_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_cron_cronjoblog_code_start_time_ran_at_time_8b50b8fa_idx ON public.django_cron_cronjoblog USING btree (code, start_time, ran_at_time);


--
-- Name: django_cron_cronjoblog_end_time_7918602a; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_cron_cronjoblog_end_time_7918602a ON public.django_cron_cronjoblog USING btree (end_time);


--
-- Name: django_cron_cronjoblog_ran_at_time_7fed2751; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_cron_cronjoblog_ran_at_time_7fed2751 ON public.django_cron_cronjoblog USING btree (ran_at_time);


--
-- Name: django_cron_cronjoblog_start_time_d68c0dd9; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_cron_cronjoblog_start_time_d68c0dd9 ON public.django_cron_cronjoblog USING btree (start_time);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: master_db_c_course__cd1b38_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_c_course__cd1b38_idx ON public.master_db_classmetadata USING btree (course_id);


--
-- Name: master_db_c_duratio_7c3de7_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_c_duratio_7c3de7_idx ON public.master_db_course USING btree (duration);


--
-- Name: master_db_c_first_n_87b10f_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_c_first_n_87b10f_idx ON public.master_db_customuser USING btree (first_name);


--
-- Name: master_db_c_male_e11d83_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_c_male_e11d83_idx ON public.master_db_customuser USING btree (male);


--
-- Name: master_db_c_status_0e5524_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_c_status_0e5524_idx ON public.master_db_classmetadata USING btree (status);


--
-- Name: master_db_c_time_st_aa0106_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_c_time_st_aa0106_idx ON public.master_db_calendar USING btree (time_start, time_end);


--
-- Name: master_db_calendar_user_id_5783cbd6; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_calendar_user_id_5783cbd6 ON public.master_db_calendar USING btree (user_id);


--
-- Name: master_db_classmetadata_course_id_a4e7e225; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_classmetadata_course_id_a4e7e225 ON public.master_db_classmetadata USING btree (course_id);


--
-- Name: master_db_classmetadata_name_e026d62c_like; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_classmetadata_name_e026d62c_like ON public.master_db_classmetadata USING btree (name text_pattern_ops);


--
-- Name: master_db_classmetadata_students_classmetadata_id_18b2f363; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_classmetadata_students_classmetadata_id_18b2f363 ON public.master_db_classmetadata_students USING btree (classmetadata_id);


--
-- Name: master_db_classmetadata_students_customuser_id_0dced2c7; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_classmetadata_students_customuser_id_0dced2c7 ON public.master_db_classmetadata_students USING btree (customuser_id);


--
-- Name: master_db_classmetadata_teacher_id_9261b72b; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_classmetadata_teacher_id_9261b72b ON public.master_db_classmetadata USING btree (teacher_id);


--
-- Name: master_db_course_name_a102d63d_like; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_course_name_a102d63d_like ON public.master_db_course USING btree (name text_pattern_ops);


--
-- Name: master_db_customuser_email_34752d40_like; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_customuser_email_34752d40_like ON public.master_db_customuser USING btree (email varchar_pattern_ops);


--
-- Name: master_db_customuser_groups_customuser_id_d4fc8e39; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_customuser_groups_customuser_id_d4fc8e39 ON public.master_db_customuser_groups USING btree (customuser_id);


--
-- Name: master_db_customuser_groups_group_id_be7a2fbb; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_customuser_groups_group_id_be7a2fbb ON public.master_db_customuser_groups USING btree (group_id);


--
-- Name: master_db_customuser_mobile_ff0a9100_like; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_customuser_mobile_ff0a9100_like ON public.master_db_customuser USING btree (mobile varchar_pattern_ops);


--
-- Name: master_db_customuser_user_permissions_customuser_id_068dff0a; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_customuser_user_permissions_customuser_id_068dff0a ON public.master_db_customuser_user_permissions USING btree (customuser_id);


--
-- Name: master_db_customuser_user_permissions_permission_id_2dbbb0f8; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_customuser_user_permissions_permission_id_2dbbb0f8 ON public.master_db_customuser_user_permissions USING btree (permission_id);


--
-- Name: master_db_s_schedul_38b7a6_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_s_schedul_38b7a6_idx ON public.master_db_session USING btree (schedule_id);


--
-- Name: master_db_s_student_f72458_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_s_student_f72458_idx ON public.master_db_session USING btree (student_id, status);


--
-- Name: master_db_s_time_st_3687ab_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_s_time_st_3687ab_idx ON public.master_db_schedule USING btree (time_start, time_end);


--
-- Name: master_db_schedule_classroom_id_7dec42c9; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_schedule_classroom_id_7dec42c9 ON public.master_db_schedule USING btree (classroom_id);


--
-- Name: master_db_session_schedule_id_1320b4ab; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_session_schedule_id_1320b4ab ON public.master_db_session USING btree (schedule_id);


--
-- Name: master_db_session_student_id_ca59e63c; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX master_db_session_student_id_ca59e63c ON public.master_db_session USING btree (student_id);


--
-- Name: taggit_tag_name_58eb2ed9_like; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX taggit_tag_name_58eb2ed9_like ON public.taggit_tag USING btree (name varchar_pattern_ops);


--
-- Name: taggit_tag_slug_6be58b2c_like; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX taggit_tag_slug_6be58b2c_like ON public.taggit_tag USING btree (slug varchar_pattern_ops);


--
-- Name: taggit_taggeditem_content_type_id_9957a03c; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX taggit_taggeditem_content_type_id_9957a03c ON public.taggit_taggeditem USING btree (content_type_id);


--
-- Name: taggit_taggeditem_content_type_id_object_id_196cc965_idx; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX taggit_taggeditem_content_type_id_object_id_196cc965_idx ON public.taggit_taggeditem USING btree (content_type_id, object_id);


--
-- Name: taggit_taggeditem_object_id_e2d7d1df; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX taggit_taggeditem_object_id_e2d7d1df ON public.taggit_taggeditem USING btree (object_id);


--
-- Name: taggit_taggeditem_tag_id_f4f5b767; Type: INDEX; Schema: public; Owner: tfc_admin
--

CREATE INDEX taggit_taggeditem_tag_id_f4f5b767 ON public.taggit_taggeditem USING btree (tag_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_master_db_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_master_db_customuser_id FOREIGN KEY (user_id) REFERENCES public.master_db_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_calendar master_db_calendar_user_id_5783cbd6_fk_master_db_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_calendar
    ADD CONSTRAINT master_db_calendar_user_id_5783cbd6_fk_master_db_customuser_id FOREIGN KEY (user_id) REFERENCES public.master_db_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_classmetadata_students master_db_classmetad_classmetadata_id_18b2f363_fk_master_db; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata_students
    ADD CONSTRAINT master_db_classmetad_classmetadata_id_18b2f363_fk_master_db FOREIGN KEY (classmetadata_id) REFERENCES public.master_db_classmetadata(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_classmetadata master_db_classmetad_course_id_a4e7e225_fk_master_db; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata
    ADD CONSTRAINT master_db_classmetad_course_id_a4e7e225_fk_master_db FOREIGN KEY (course_id) REFERENCES public.master_db_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_classmetadata_students master_db_classmetad_customuser_id_0dced2c7_fk_master_db; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata_students
    ADD CONSTRAINT master_db_classmetad_customuser_id_0dced2c7_fk_master_db FOREIGN KEY (customuser_id) REFERENCES public.master_db_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_classmetadata master_db_classmetad_teacher_id_9261b72b_fk_master_db; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_classmetadata
    ADD CONSTRAINT master_db_classmetad_teacher_id_9261b72b_fk_master_db FOREIGN KEY (teacher_id) REFERENCES public.master_db_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_customuser_user_permissions master_db_customuser_customuser_id_068dff0a_fk_master_db; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_user_permissions
    ADD CONSTRAINT master_db_customuser_customuser_id_068dff0a_fk_master_db FOREIGN KEY (customuser_id) REFERENCES public.master_db_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_customuser_groups master_db_customuser_customuser_id_d4fc8e39_fk_master_db; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_groups
    ADD CONSTRAINT master_db_customuser_customuser_id_d4fc8e39_fk_master_db FOREIGN KEY (customuser_id) REFERENCES public.master_db_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_customuser_groups master_db_customuser_groups_group_id_be7a2fbb_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_groups
    ADD CONSTRAINT master_db_customuser_groups_group_id_be7a2fbb_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_customuser_user_permissions master_db_customuser_permission_id_2dbbb0f8_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_customuser_user_permissions
    ADD CONSTRAINT master_db_customuser_permission_id_2dbbb0f8_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_schedule master_db_schedule_classroom_id_7dec42c9_fk_master_db; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_schedule
    ADD CONSTRAINT master_db_schedule_classroom_id_7dec42c9_fk_master_db FOREIGN KEY (classroom_id) REFERENCES public.master_db_classmetadata(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_session master_db_session_schedule_id_1320b4ab_fk_master_db_schedule_id; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_session
    ADD CONSTRAINT master_db_session_schedule_id_1320b4ab_fk_master_db_schedule_id FOREIGN KEY (schedule_id) REFERENCES public.master_db_schedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: master_db_session master_db_session_student_id_ca59e63c_fk_master_db; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.master_db_session
    ADD CONSTRAINT master_db_session_student_id_ca59e63c_fk_master_db FOREIGN KEY (student_id) REFERENCES public.master_db_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: taggit_taggeditem taggit_taggeditem_content_type_id_9957a03c_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.taggit_taggeditem
    ADD CONSTRAINT taggit_taggeditem_content_type_id_9957a03c_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: taggit_taggeditem taggit_taggeditem_tag_id_f4f5b767_fk_taggit_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: tfc_admin
--

ALTER TABLE ONLY public.taggit_taggeditem
    ADD CONSTRAINT taggit_taggeditem_tag_id_f4f5b767_fk_taggit_tag_id FOREIGN KEY (tag_id) REFERENCES public.taggit_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

