# Generated by Django 3.2.3 on 2021-06-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('date', models.TextField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='class_metadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('status', models.TextField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='class_student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='class_teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('desc', models.TextField()),
                ('short_desc', models.TextField()),
                ('type', models.TextField()),
                ('duration', models.SmallIntegerField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='metatable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('dashboard', models.BooleanField()),
                ('kanban', models.BooleanField()),
                ('setting', models.BooleanField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.TextField(unique=True)),
                ('uid', models.TextField(unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birth_date', models.BigIntegerField()),
                ('email', models.TextField(unique=True)),
                ('mobile', models.TextField(unique=True)),
                ('gender', models.BooleanField(null=True)),
                ('password', models.TextField()),
                ('address', models.TextField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
                ('role_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.FloatField()),
                ('time_end', models.FloatField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
                ('classroom_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database_app.class_metadata')),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('short_desc', models.TextField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
                ('table_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.metatable')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['type'], name='database_ap_type_48cbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['duration'], name='database_ap_duratio_5c9d91_idx'),
        ),
        migrations.AddField(
            model_name='class_teacher',
            name='classroom_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database_app.class_metadata'),
        ),
        migrations.AddField(
            model_name='class_teacher',
            name='teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database_app.user'),
        ),
        migrations.AddField(
            model_name='class_student',
            name='classroom_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database_app.class_metadata'),
        ),
        migrations.AddField(
            model_name='class_student',
            name='student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database_app.user'),
        ),
        migrations.AddField(
            model_name='class_metadata',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database_app.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database_app.session'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database_app.user'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='database_ap_first_n_ab1ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='database_ap_last_na_97ae04_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['birth_date'], name='database_ap_birth_d_c26491_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gender'], name='database_ap_gender_385f60_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role_id'], name='database_ap_role_id_073ced_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['time_start', 'time_end'], name='database_ap_time_st_8f01b5_idx'),
        ),
        migrations.AddIndex(
            model_name='class_metadata',
            index=models.Index(fields=['status'], name='database_ap_status_672463_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='database_ap_status_597925_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student_id', 'date'), name='unique_attendance'),
        ),
    ]
