# Generated by Django 3.2.6 on 2021-09-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_db', '0002_auto_20210824_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
